### ISSUE TITLE
[HELP] bcrypt is pushing me into a bottomless pit of despair

### ISSUE THREAD

**Issue by mshockz** [ST0507-ades/help#10]
## (Background) I have been trying to...
Do `bcrypt.compare()` for some recovery_codes(plaintext) and their hashed value in the database. Users can generate a set of 8 recovery codes that they can use to retrieve their account in the case they forgot their password. My recovery code verification function currently takes in the plaintext, retrieves an array of hashed codes from the db and via a for loop, does `bcrypt.compare()` between the plaintext and each value in the array. I am expecting a "true" response from my `bcrypt.compare()` for one repetition of the for loop.

## But instead, I am seeing...
False for all instances of `bcrypt.compare()` despite the plaintext being the right one

I have checked out possible solutions on github and stackoverflow, but they have not been helpful in solving this issue. I have tried downscaling the size of my codes to 8 instead of 32, tried trimming my input and use `bcrypt.compareSync()` but I was met with the same result

## Screenshot of logs (browser console, inspect network, and/or VSCode terminal)
part of my verifyCode function:
![image](https://user-images.githubusercontent.com/96334916/181674280-146c3cab-9afe-4963-a602-7d53af1369dc.png)

what the user will see after generating the recovery codes[plaintext] (currently, it automatically downloads the set of codes in a txt file for the users)
![image](https://user-images.githubusercontent.com/96334916/181674502-ce27e389-216f-4a1c-ad34-e82d7baa641a.png)

what i have in my postman when testing the code(this should return true for one `bcrypt.compare()` instance):
![image](https://user-images.githubusercontent.com/96334916/181674717-10fdd999-2993-45a4-a434-633ad09934a7.png)

what i see in vsc after sending the information over:
![image](https://user-images.githubusercontent.com/96334916/181674929-aaf02a22-72d2-414a-8b91-fd808eb47f23.png)

ps. my generate code function bugs out sometimes but its not a big deal and all my changes related to this issue is in my fork

**Comment by jeremiah-ang** [comment]
I have 2 questions in mind 

1. What is the data type of column "recovery_code" in the database? 
2. Why does your for-loops increment by 2 in each iteration?

**Comment by jeremiah-ang** [comment]
Reassign to me when you replied.

**Comment by mshockz** [comment]
> I have 2 questions in mind
> 
> 1. What is the data type of column "recovery_code" in the database?
> 2. Why does your for-loops increment by 2 in each iteration? 

1.  it is of json type

2. it is part of something redundant i did to debug the generate code function(this was related to the small issue that i mentioned above) 

the full generate code function for reference:
![image](https://user-images.githubusercontent.com/96334916/181698155-3aaad780-867c-45db-b6f5-808c17d5c54c.png)

the compArray consists of alpha-numeric characters

**Comment by jeremiah-ang** [comment]
@GGsendhelpGG hmmm I do not have any intelligent guess currently. Except for "are you sure you're getting the codes from the right user?" 

Can you try set up some tests right after you insert? 

That is, instead of calling the callback immediately after successful insert, you simulate the verify process with a random code. 

And I notice you're doing asynchronous tasks within synchronous for-loops, is that intentional?

**Comment by jeremiah-ang** [comment]
Dropped
