### ISSUE TITLE
[HELP] data is undefined for when useQuery is not used

### ISSUE THREAD

**Issue by shayaanak32** [ST0507-ades/help#11]
## (Background) I have been trying to...
![image](https://user-images.githubusercontent.com/97072991/181722168-14f9fca0-378b-48bb-80ad-013796f8333d.png)

This is my code, where I have a button which triggers a refetch to the useQuery function to fetch game data from the database.
In the code for the graph as you can see I am accessing the data variable and I am trying to use it to plot the graph(one of the things i did with the data was data.length)

## But instead, I am seeing...
![image](https://user-images.githubusercontent.com/97072991/181722566-df6196a8-7e2e-48a5-81a2-4c7034eef9d8.png)

my suspicion is that since the component runs linearly downwards, since the useQuery has not been run yet, data will not be defined, so since i use the data variable after the code I have for the button to refetch, useQuery is not run and data isn't defined, but I am not sure. I have also tried putting a if condition around the graph code such that it would run if isFetched woulkd equal true, but that did not work too.

## Additional Methods tried
i tried making a separate graph component
![image](https://user-images.githubusercontent.com/97072991/181723462-bb00206f-f6a2-4085-ba7f-43c173415b43.png)

![image](https://user-images.githubusercontent.com/97072991/181723511-209b8578-bf95-4c3a-8038-8646dc74d625.png)
(with me trying to pass data as props)

But ultimately I still get the same result.

**Comment by jeremiah-ang** [comment]
Firstly, hooks shouldn't be inside any bracket scopes 

Secondly, useEffect basically means, to trigger an effect when one of the dependencies changes, it is undefined at the start so you can put an if-statemsnt in the useEffect to carry on only when the data is defined. 

```
useEffect(() => {
    if(data) {
        ....
    }
}, [data])
````

**Comment by shayaanak32** [comment]
I tried it just now like that and it doesn't work, like nothing shows on screen, when the button to view graph is supposed to show

**Comment by jeremiah-ang** [comment]
Because there's an error with the component hence the button is not showing.

What's the error you get when you do it the way I described?

**Comment by jeremiah-ang** [comment]
Oh wait. Enabled is false? So no query is made? Then what do you expect data to be?

**Comment by shayaanak32** [comment]
I thought enabled being false meant that there would be no auto fetching all the time, and that we would only trigger the fetch through either something like refetch() function that I used which comes as a result of an action( eg. button onClick). That was my bad I mistook its use. But I still get the same values

**Comment by jeremiah-ang** [comment]
What do you mean by "but I still get the same value"?

Can send more screenshots of what you get after you tried fixing?

**Comment by shayaanak32** [comment]
Updated Code
![image](https://user-images.githubusercontent.com/97072991/181878425-55261501-89f8-494d-95c3-df20ad4f540a.png)

Result 

![image](https://user-images.githubusercontent.com/97072991/181878438-685af338-2ce9-4066-9c8c-ac9e9c374fe5.png)

**Comment by shayaanak32** [comment]
Tried Switching up the code a little:

![image](https://user-images.githubusercontent.com/97072991/181878642-77ea5678-85ba-4c0c-8805-210187a814ff.png)

I get the same thing

![image](https://user-images.githubusercontent.com/97072991/181878695-aa5d5502-2810-4548-9b82-b9df18beb540.png)

**Comment by jeremiah-ang** [comment]
~The error is pointing at line 12 and line 31 right? Can we see that section?~

Nvm I realize it's all here

**Comment by jeremiah-ang** [comment]
Are you sure you're not looking at outdated errors? 

I suspect you're looking at the wrong thing all along, can you click on the `LeaderboardGraphBtn.js:31:53` to see which line they are referring to? 

Take a ss too.
