### ISSUE TITLE
[HELP] how to reference a component with props in the <script> tag of my html file

### ISSUE THREAD

**Issue by shayaanak32** [ST0507-ades/help#12]
## (Background) I have been trying to...

I want to reference my Song Player component here to all of the different pages and I am not sure how to reference it
![image](https://user-images.githubusercontent.com/97072991/182022137-3d43d61d-e804-42df-a945-0930af58d63d.png)

##  I am seeing...
![image](https://user-images.githubusercontent.com/97072991/182022161-5f2f9eea-0dea-4e53-9fb6-973c4ccfc930.png)

**Comment by jeremiah-ang** [comment]
Browser can't understand jsx. If you're using jsx, you have to use babel to compile it first.

**Comment by shayaanak32** [comment]
Hm, because I would like for the component to be used on the front-end and I needa pass in props as well into it, so how can I achieve this?

**Comment by jeremiah-ang** [comment]
> because I would like for the component to be used on the front-end

All your React components are used in the front-end. 

> I needa pass in props as well into it

You pass props by doing `<MyComponent myProps={...} />`

However, the above syntax uses JSX, so whichever file you write that in, has be to compiled by babel into pure javascript before importing to the HTML (You cannot have a `<script>` tag with JSX)

**Comment by shayaanak32** [comment]
so I cannot use props, and I need to reference the file like I would conventionally whe dealing w/ cpmponents

**Comment by jeremiah-ang** [comment]
> so I cannot use props, and I need to reference the file like I would conventionally whe dealing w/ components

You can use props, how did you conclude that you can't use props? 

You simply have to move your scripts to a file, run it through babel, and import the compiled version.

**Comment by shayaanak32** [comment]
no I know that but the thing is this is a standalone component, so it has no parent component that I need to render it inside of in order to get the functionality to work

**Comment by jeremiah-ang** [comment]
Relook at how we did it in the tutorial.

**Comment by jeremiah-ang** [comment]
Is this solved?

**Comment by shayaanak32** [comment]
Oops frogot to close. But baically rendered in a parent component and it worked out fine
