### ISSUE TITLE
[HELP] d3 positioning issues

### ISSUE THREAD

**Issue by shayaanak32** [ST0507-ades/help#13]
## (Background) I have been trying to...

I am trying to make the x and y axis of my svg align with each other, but that is not working at the minute 

![image](https://user-images.githubusercontent.com/97072991/182070876-c5f4a59d-e965-4315-9d15-31c0ae7eaa1b.png)

The y axis is not showing up how i want it to, and I am unsure as to how I can get it to link together, as you can see in the picture, the axis is barely pointing upwards.

## Screenshot of logs and explanation of some code
![image](https://user-images.githubusercontent.com/97072991/182072142-ef4e708e-9bce-484f-9acb-1001a33fb8b6.png)
I assigned a ref to the svg element
![image](https://user-images.githubusercontent.com/97072991/182072173-a59e45cf-f927-4744-abe0-fab0c12ff2aa.png)
these are the dimensions of the chart

![image](https://user-images.githubusercontent.com/97072991/182072231-93b57c69-aeda-4915-9c3e-354238846478.png)
this right here is the code that generates the Y Axis, basically to explain what happens here, a <g> element is appended, and the axis is translated upwards by 70px because of the (-70), and then this axis is created by calling the axisLeft method. Inside y there is a domain which is essentially the degree of values, so I set it to this:
![image](https://user-images.githubusercontent.com/97072991/182072414-727b5901-3601-4a1f-a5df-04c2d90701e5.png)
which means the graph goes to the maximum game value.

**Comment by jeremiah-ang** [comment]
Where is the axis? O.O

**Comment by shayaanak32** [comment]
![image](https://user-images.githubusercontent.com/97072991/182074035-396144ab-49dd-4587-8961-5f648a27fe23.png)
 I know why the axis on the left is really small, it is because its range in pixels in only abt 90

**Comment by shayaanak32** [comment]
![image](https://user-images.githubusercontent.com/97072991/182074474-0843f1c5-66fe-48ae-9041-572c9a354165.png)
This is what happens when I increase the range of the y axis
![image](https://user-images.githubusercontent.com/97072991/182074588-e450470e-09d5-4e5c-b5c6-dffdcfb43593.png)
 like this

**Comment by jeremiah-ang** [comment]
So is this solved?

**Comment by shayaanak32** [comment]
no it isn't I can't figure out why the axis goes downwards like that, when it should be going up

**Comment by jeremiah-ang** [comment]
Solved in class
