### ISSUE TITLE
[HELP] Trying to get data to show in frontend

### ISSUE THREAD

**Issue by Kurohitsugi90** [ST0507-ades/help#15]
## (Background) I have been trying to...

use useQuery and get the data out to display on frontend

## But instead, I am seeing...

that data is undefined, but I'm able to get it in the fetch result and backend
![image](https://user-images.githubusercontent.com/95752920/182348845-b12504cc-0143-4155-9645-a579ea8cd75b.png)
*data, isLoading and error is printed respectively. The object Object is the array below*

## Screenshot of logs (browser console, inspect network, and/or VSCode terminal)

image of ModuleFiles.js:
![image](https://user-images.githubusercontent.com/95752920/182348949-aaa2ad5e-340d-4011-a307-6df24a8e5225.png)

image of ModuleFilesApi.js:
![image](https://user-images.githubusercontent.com/95752920/182349428-6cb23f5b-8e33-4918-9117-b3cb6d6cb25b.png)

network:
![image](https://user-images.githubusercontent.com/95752920/182349554-b8d0c115-2e60-4809-8dcb-e6580cc40798.png)

**Comment by jeremiah-ang** [comment]
`data` is **initially** undefined. Only after the component is first mounted, then the query is executed, so when the component is first mounted, you will find `isFetching` and `isLoading` to be `true`. 

After the data has been fetched, the component will re-render and then `data` will be the value and `isFetching`/`isLoading` will become `false`. 

So you would want to do a `if-else` to show Loading and data respectively.

**Comment by Kurohitsugi90** [comment]
Ouhh I see, that's why I'm seeing two sets of it.

Hmm then, is the `if-else` I did alright?
![image](https://user-images.githubusercontent.com/95752920/182370168-5ae70d9c-817d-4780-bd83-46d4b0d0bc2d.png)

If it is, then I'm still unsure why `data` is still missing, as *No files found* is being displayed:
![image](https://user-images.githubusercontent.com/95752920/182372174-d7f62d92-1590-41dd-a44d-c6b54377d45f.png)

Is it the way I'm returning the data from ModuleFilesApi, perhaps?

**Comment by jeremiah-ang** [comment]
It looks right to me, any other errors?

**Comment by Kurohitsugi90** [comment]
There's no other errors shown so far :/

The preview in network and `console.log` in server is displaying the intended result, still `undefined` in `data`
Tried using `onSuccess` and `onError` in the `useQuery`
![image](https://user-images.githubusercontent.com/95752920/182519005-5711f4af-e4ca-48b1-931e-e6a0c94c01c7.png)
Seems like the `onSuccess` was fired
![image](https://user-images.githubusercontent.com/95752920/182519778-dc504b0f-ccf2-427a-8b53-99b14be78bc4.png)

**Comment by Kurohitsugi90** [comment]
Update: 
Got it working, all I need was a `return`  to the fetch function:
![image](https://user-images.githubusercontent.com/95752920/182573197-7aa305cd-4003-4a00-bcc1-99deca591c6e.png)
Huge thanks to wei yang :)))

(or just don't add the brackets)
