### ISSUE TITLE
[HELP] Using type="module" instead of type="text/javascript" for JS page and React component in html imports

### ISSUE THREAD

**Issue by juliaalim** [ST0507-ades/help#4]
## (Background) I have been trying to...
use functions from my injected react page in my html page and vice-versa (Similar to your addRows/getRows and updateResult functions in your "Adding React to a Website" brightspace video. However in my html page, the class.js and react component ClassPreview.js page is type="module" instead of type="text/javascript" like in your video. ![image](https://user-images.githubusercontent.com/68234847/179398479-3706a928-a13f-4547-b136-5481893a7a3c.png)

## But instead, I am seeing...
that I am not able to use functions in the react component e.g createInfoPreview (meant to render the class info onto the preview area) in the javascript file class.html as it is not defined. 
![image](https://user-images.githubusercontent.com/68234847/179399699-83188772-d9a1-4a30-ace1-6ff632d91e53.png)

**Image of src>ClassPreview.js react component file where createInfoPreview function was declared in line 53 and initialized in line 67:**
![image](https://user-images.githubusercontent.com/68234847/179399192-14c00c87-5c32-4cdf-9115-2730df83639a.png)

**Image of js>class.js file where createInfoPreview was used in line 314:**
![image](https://user-images.githubusercontent.com/68234847/179399234-7f4c38df-9508-4331-b89d-3c06814f30cd.png)

**Image of Inspect network:**
![image](https://user-images.githubusercontent.com/68234847/179399511-3e29d444-800c-4944-b4d4-255fadcf3e6a.png)

**Using text/javascript**
I have tried to use the class.js and react component imports as text/javascript like your video, however I am not able to import other js pages outside a module.  I need to import items like verifyUser.js page so I am not able to remove the import statement. 
![image](https://user-images.githubusercontent.com/68234847/179399675-781908ce-2ef8-499f-abb5-20b032fe26c1.png)

**Image of inspect network:**
![image](https://user-images.githubusercontent.com/68234847/179399594-4adcf8ce-6efe-4c8c-a06b-f6f58baf5671.png)

**Comment by jeremiah-ang** [comment]
Set the function as a property of `window` to make it global. 

E.g. 

```
window.createInfoPreview = function (...) { ... } 
```

Read more: https://medium.com/codex/global-variables-and-javascript-modules-ce674a869164#:~:text=A%20global%20variable%20is%20a,properties%20as%20shown%20in%20windowProperties.

You can also check with kehan and vernel on this, they asked smth similar before. 

(Reassign the issue to me if you have any follow up questions)

**Comment by juliaalim** [comment]
Thank you!
