### ISSUE TITLE
[HELP] Issue with new ReactQuery CDN

### ISSUE THREAD

**Issue by VielenKaat** [ST0507-ades/help#5]
## (Background) I have been trying to...
Update the react query link to the new version 
https://unpkg.com/@tanstack/react-query@4.0.0/build/umd/index.production.js

Can import the new ReactQuery 
## But instead, I am seeing...
![image](https://user-images.githubusercontent.com/29939588/179923765-5be2a576-5459-4f70-b217-2e5f1c4d5f72.png)

This is what happens when I useQuery to run

![image](https://user-images.githubusercontent.com/29939588/179924003-793a697a-1c01-4d04-87bf-c96aeed1d1f0.png)

Code for fetching data works

## Screenshot of logs (browser console, inspect network, and/or VSCode terminal)

Switch to latest version of babel cli, should be latest since the code can support fragment shorthands now 
![image](https://user-images.githubusercontent.com/29939588/179924223-d578422b-9e15-4b6b-b947-71eb3d39778c.png)

Update the script for running the react compiler with new preset
![image](https://user-images.githubusercontent.com/29939588/179924429-462ed554-3438-4b4f-97be-0ce9b67a3fd5.png)

Index.html imports
![image](https://user-images.githubusercontent.com/29939588/179925203-88b152d9-821b-49d2-a248-536af1ae386a.png)

Screenshot of inspect network
![image](https://user-images.githubusercontent.com/29939588/179925287-30fe2512-f749-4086-88f5-c812647808ad.png)

**Comment by jeremiah-ang** [comment]
Can you click on the `useBaseQuery.ts:81:3` and see what is `undefined`? Send a screenshot ba.

**Comment by VielenKaat** [comment]
the base query error comes with the https://unpkg.com/@tanstack/react-query@4.0.0/build/umd/index.production.js link, https://unpkg.com/@tanstack/react-query@4.0.0 gives the same error but at a different file

**Using https://unpkg.com/@tanstack/react-query@4.0.0/build/umd/index.production.js  link**
![image](https://user-images.githubusercontent.com/29939588/179930463-b9fce295-97b5-4e55-b815-df3a57c3babe.png)

**Using https://unpkg.com/@tanstack/react-query@4.0.0 link**
![image](https://user-images.githubusercontent.com/29939588/179931043-08d5ecff-2383-4953-b9be-fd984468cca5.png)

**Comment by jeremiah-ang** [comment]
Can you try this link instead? 

https://unpkg.com/react-query@3.39.2/dist/react-query.production.min.js

**Comment by VielenKaat** [comment]
ya, the link works, thanks!
