### ISSUE TITLE
[HELP] Trying to resolve CORS error

### ISSUE THREAD

**Issue by Kurohitsugi90** [ST0507-ades/help#6]
## (Background) I have been trying to...
test out my group's website on Netlify after deploying frontend and backend.

## But instead, I am seeing...
a CORS error when trying to login to the website.
![image](https://user-images.githubusercontent.com/95752920/180696018-68e092ca-bd2b-4745-bc67-503468f3ac78.png)

Things we added in backend:
- multer
![image](https://user-images.githubusercontent.com/95752920/180699621-78545266-f50e-4cae-9128-fd1ee9eb2af9.png)
- cloudinary
![image](https://user-images.githubusercontent.com/95752920/180699671-2c18f98b-295e-4b0e-8dcd-4f419149ba47.png)
- prisma

All .env configs are added to heroku.

Things we added in frontend:
- React for all pages, TinyMCE scripts for module management page
![image](https://user-images.githubusercontent.com/95752920/180699940-2039f149-8c74-4e56-8178-dc56b025cd60.png)

## Screenshot of logs (browser console, inspect network, and/or VSCode terminal)
Inspect network:
![image](https://user-images.githubusercontent.com/95752920/180696543-01db48d6-ee0c-4e24-a9d8-06b6566b4197.png)
![image](https://user-images.githubusercontent.com/95752920/180696747-f890b583-0f2c-4898-abe7-c39094fffe05.png)

Here's login.js:
![image](https://user-images.githubusercontent.com/95752920/180697087-a0b516bb-57bd-4a54-a7cb-c5be57e169fc.png)

**Comment by jeremiah-ang** [comment]
The response code is 503 service unavailable, looks like your heroku app is not running, can you check your heroku logs?

**Comment by Kurohitsugi90** [comment]
Ohhhh now I see why, the file naming caused the crash🤦
![image](https://user-images.githubusercontent.com/95752920/180703277-4d04745d-fb52-4498-bccc-9ad839ea72bd.png)

Thanks for the heroku logs reminder! Hmm is there any reason why CORS error is shown, instead of something like 'cannot find this file at...' like in the logs? The group thought that the error is quite random

**Comment by jeremiah-ang** [comment]
To heroku, it's basically "the app crashed." It doesn't know why it crashed. 

And when it's crashed, heroku takes over the handling of request and is not able to handle cross origin request. Hence the CORS error.
