### ISSUE TITLE
[HELP] d3 Import is not showing & useRef is not being recognised

### ISSUE THREAD

**Issue by shayaanak32** [ST0507-ades/help#8]
## (Background) I have been trying to...
I have used the unkpg version of d3 to be used in my project. I opened the link in the browser and saved it all to my project directory. I then referenced this particular script using the <script> tag in my html file like so: 

![image](https://user-images.githubusercontent.com/97072991/180940539-1b9050a3-19f9-41e6-8289-12647e0729c4.png)

On top of this, what I have also done is that I have referenced d3 inside my component file like this: 

![image](https://user-images.githubusercontent.com/97072991/180941086-0d6166f9-464a-4876-a4ff-d33e96266834.png)

and this 
![image](https://user-images.githubusercontent.com/97072991/180941168-d6f023c0-f022-4d7b-aad2-96a7579570b6.png)

Another small problem is that my useRef is not being recognised in the browser, even though I have imported it in my component,lik so:
![image](https://user-images.githubusercontent.com/97072991/180942248-3a1ebbd4-b4a8-4dbf-8609-cd5897f4054b.png)

## But instead, I am seeing...

but still I get this showing in my console

![image](https://user-images.githubusercontent.com/97072991/180941682-2b283c2b-e123-457d-945d-1426867d9ed7.png)

this means that the d3.select() method is unable to be recognised, so there fore, I feel like the d3 isnt present or something, for this not to throw an error, but I am not sure.

P.S I have also installed d3, and the dependancy shows in the package.json file

Also, this is how the useRef error looks like 

![image](https://user-images.githubusercontent.com/97072991/180942382-7d9e144c-98b7-4c34-be51-c2e2ba0fc27c.png)

(the line that it is pointing to is this:)
![image](https://user-images.githubusercontent.com/97072991/180942571-e6e52c2e-0571-48c2-abdf-c949335f7a18.png)

**Comment by jeremiah-ang** [comment]
I tried setting up a simple website

<img width="608" alt="image" src="https://user-images.githubusercontent.com/17397188/180957685-af62e9d0-c550-4e8a-a1a5-0a622a3d378c.png">

This is the HTML that imports D3 from the CDN and a module called `main.js`

<img width="598" alt="image" src="https://user-images.githubusercontent.com/17397188/180957959-d1e6ac14-2837-4fae-b55f-4c3930ca98ac.png">

This is `main.js`, it simply `console.logs` `d3.select`

<img width="665" alt="image" src="https://user-images.githubusercontent.com/17397188/180958180-3cd85ecc-8b5a-47e4-965d-5f42a8fa17dd.png">

This is the output, basically showing that d3 is indeed accessible on the global scope, and the method `select` is there too. 

----

# I think you might have a deeper issue with perhaps the way your scripts are setup. 

You really shouldn't be doing things like 

```
const x = x; 
```
It's not sensible as you are trying to create a new variable (i.e. it does not exist yet), with its own value (which again does not exist yet). 

The d3 package being shown in your `package.json` is irrelevant as when the browser opens and loads the HTML file, it does not use the node packages. We introduced `package.json` mainly for the use of `babel` a behind-the-scene pre-processing step before the browser takes over.

**Comment by jeremiah-ang** [comment]
Re-assign the issue to me after you replied with more findings on your own, or close the issue if you managed to solve it.

**Comment by jeremiah-ang** [comment]
@shayaanak32 is this resolved already?

**Comment by shayaanak32** [comment]
resolved, forgot to close
