### ISSUE TITLE
[HELP] Why inside my response, it don't have response.data

### ISSUE THREAD

**Issue by beh780** [ST0507-ades/help#9]
### Why  inside my response, it don't have response.data

## Which instruction are you referring to? (Screenshot)
![image](https://user-images.githubusercontent.com/82916816/180947149-15535b7e-b956-407b-9caf-82652a1bdaba.png)
![image](https://user-images.githubusercontent.com/82916816/180947274-5e66e60b-be29-4294-a616-58be0c479821.png)

**Comment by jeremiah-ang** [comment]
Because the response body needs to be extracted from the HTTP response using either `response.json()` (if the body is known to follow the json format) or `response.text()`. 

More example: https://developer.mozilla.org/en-US/docs/Web/API/Response/json

**Comment by jeremiah-ang** [comment]
Reassign the issue to me or close the issue if you managed to solve the problem. Subsequently, please use `HELP` for coding related issues and `ASSIGNMENT` only for questions about the assignment specification itself.

**Comment by beh780** [comment]
But now my problem is the data no return into response

**Comment by jeremiah-ang** [comment]
@beh780 is it because the server is not sending anything? You closed it because you solved it?

**Comment by beh780** [comment]
yes,i solve it

**Comment by beh780** [comment]
i  find that use axios can get the data
